name: "PR Test Options Commenter"
description: "Adds a comment to PRs with checkbox options for triggering expensive tests."
author: "You"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  checkboxes:
    description: |
      Comma separated list of checkboxes.
      Simple example: "Test1, Test2"
      Advanced example: "Test1=Test #1 description, Test2=Test #2 description"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
