name: "Add checkbox to PR"
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: List files
        run: |
          pwd
          find .
      - uses: ./pr-add-checkbox
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          checkboxes: "test-1=Test 1 description, test-2=Test 2 description"
