name: "Add checkbox to PR"
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: dueckminor/pr-checkbox-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
